"""Added association table

Revision ID: 475abb8d725d
Revises: d4405187b83a
Create Date: 2024-02-03 16:30:35.795014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475abb8d725d'
down_revision = 'd4405187b83a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_offered_job_association',
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('offered_job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offered_job_id'], ['offered_jobs.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_offered_job_association')
    # ### end Alembic commands ###
